### ISSUE TITLE
[feature] parameter transformation

### ISSUE THREAD

**Issue by backbone87** [iltar/http-bundle#14]
Use case:
- Entities have UUIDs as PK.
- Within the application domain UUIDs are stored in their default string representations (32 chars hex + 4 dashes)
- to get shorter URLs the UUIDs should be represented as base64url

Would this be a feature that is possible to integrate in this bundle? If we can find a viable solution, i can also provide a PR.

Some thoughts regarding implementation:
- The transformation to use must be specified on a per parameter basis within the route definition. (requirements? defaults?)
- Should it be allowed to specify multiple transformations (a chain) or should the transformation chain be built externally and each parameter can only use exactly one transformation
- Reverse transformation must occur very early so things like ParamConverter gets the "canonical" representation

**Comment by iltar** [comment]
I personally have never used UUID before so my knowledge about them is limited. However, the way you describe it, it sounds simple enough. You can register it with a higher priority than the doctrine [`EntityIdResolver`](https://github.com/iltar/http-bundle/blob/master/src/DoctrineBridge/Router/EntityIdResolver.php).

 > The transformation to use must be specified on a per parameter basis within the route definition. (requirements? defaults?)

In the end it does nothing more than transforming the Entity into a string representation, which at the moment is simply the getId() method. The router will still handle [the generation](https://github.com/iltar/http-bundle/blob/master/src/Router/ParameterResolvingRouter.php#L64) so that's your feature set.

> Should it be allowed to specify multiple transformations (a chain) or should the transformation chain be built externally and each parameter can only use exactly one transformation

It depends on how you want to represent it. Is there a default way of showing the UUID in the url?

> Reverse transformation must occur very early so things like ParamConverter gets the "canonical" representation

That's pretty much up to how you implement the ParameterConverter. I wasn't planning on adding ParamConverters in this package and I don't think the reverse transformation belongs anywhere else. A good example would be that a parameter converter checks if it can be decoded back into the UUID and if there's an entity with that given ID.

I can see the need for a UUID converter; I've seen questions coming by on Freenode#symfony how people would represent that in the URL. If there's no standard, maybe a configuration node could provide you the option to define a transformer which can do both ways. This would make it fairly easy to implement in the ParamConverter as well.

**Comment by backbone87** [comment]
well the base64url encoding can be used for any binary data. it is not limited to UUIDs. there are also other encodings like base36 (not case sensitive) that could be useful. thats why i want this feature to be transparent. you just configure the transformation to apply to a certain parameter in the route definition. and the rest is done by the route generator and the route matcher (?).

**Comment by iltar** [comment]
Feel free to make a PR so we can check if this is really beneficial

**Comment by iltar** [comment]
@backbone87 are you still interested in making a PR for this or shall I close the issue?

**Comment by iltar** [comment]
Closing as it seems the feature is not wanted anymore

**Comment by backbone87** [comment]
sorry for not replying, but the feature isnt currently on the top of the list of the project i work for. maybe i will come back to it, another time.
